# Generated by Django 6.0.2 on 2026-04-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
