# Generated by Django 6.0.2 on 2026-05-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='edited',
        ),
    ]
