# Generated by Django 6.0.2 on 2026-05-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_file_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pinned_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_in_rooms', to='chat.message'),
        ),
    ]
