# Generated by Django 6.0.2 on 2026-05-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_room_pinned_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='pinned_message',
        ),
    ]
