# Generated by Django 6.0.2 on 2026-05-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_room_pinned_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
    ]
